taka-tuos/nanotodon

nanotodon.c
とりあえず gcc の標準を消してみました。
以下の警告は残っています。
warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
char *t = json_object_get_string(notify_type);
=> Supress gcc warnings.

Makefile.in
- BSD make でも動くように修正
- make clean で -f を指定してエラーを抑制
- make clean で ${TARGET} の nanotodon バイナリも削除
=> Fix makefile warnings

nanotodon.c
以下の警告の修正です
```
nanotodon.c: In function 'do_htl':
nanotodon.c:629:10: warning: unused variable 'p' [-Wunused-variable]
char *p = strdup(json_object_to_json_string(obj));
^
nanotodon.c: In function 'main':
nanotodon.c:659:8: warning: unused variable 'key' [-Wunused-variable]
char key[256];
```
=> Fix unused variable warnings.

Makefile.in, nanotodon.c
以下の警告の修正:
```
nanotodon.c: In function 'do_oauth':
nanotodon.c:512:18: warning: unknown conversion type character 'w' in format [-Wformat=]
sprintf(fields, "client_id=%s&client_secret=%s&grant_type=authorization_code&code=%s&scope=read%20write%20follow", ck, cs, code);
^
nanotodon.c:512:18: warning: format '%f' expects a matching 'double' argument [-Wformat=]
nanotodon.c:512:18: warning: unknown conversion type character 'w' in format [-Wformat=]
nanotodon.c:512:18: warning: format '%f' expects a matching 'double' argument [-Wformat=]
```
この認証URLが実際に使われているのかどうかは確認してません。
=> Fix printf format strings

nanotodon.c
curses で規定されているデフォルトの背景色を使用するようにします。
これで mlterm 等の壁紙グラフィックも透過表示されます。
=> Use default background color.

Makefile, config.c, config.h, nanotodon.c
設定ファイルが$HOME直下にぶちまけられて鬱病になりそうだったので、サブディレクトリを作成するような対応を入れました。
ついでに、XDG Base Directory準拠っぽく作成するようにしてありますが、これは好みの問題もありそうなのでmake時の定数や環境変数なんかで切り替えられる形にするのも良いかもしれませんね。
=> 設定のディレクトリ化とXDG Base Directoryサポート

Makefile
ライブラリの指定について、以下のマイナーな修正です
* -lc は標準でリンクされるので指定不要では
* -lm はシステム標準ライブラリなので最後にしたい
(仮に他のオプションのライブラリが libm 関数を使用していた場合、かつ、 static link の場合は順序依存があるのでリンクに失敗する)
=> Minor fix for LIBS.

nanotodon.c
#17 以外にも free() が足りてないような気がしたので適当に足してみました。
変数のスコープをちゃんとわかっていないので場所がダメかも。
あと、これは別 issue で書くべきかもしれませんが
```streaming_recieved()``` の
```c
char **json_recieved = NULL;
int json_recieved_len = 0;
// ストリーミングで受信したJSON(接続維持用データを取り除き一体化したもの)
void streaming_recieved(void)
{
json_recieved = realloc(json_recieved, (json_recieved_len + 1) * sizeof(
char *));
json_recieved[json_recieved_len] = strdup(streaming_json);
```
にある ```json_recieved``` と ```json_recieved_len``` って使われているんでしょうか?
(あと、ますます関係ないですが ```recieved``` じゃなくて ```received``` ですね……)
=> Plug more malloc() and strdup() leaks.

nanotodon.c
そもそも UA として curl でいいのかというのをわかっていませんが、
7.47.0 決め打ちよりは良いかと。
=> Use LIBCURL_VERSION in <curl/curlver.h> for CURLOPT_USERAGENT.

nanotodon.c
"🔃 Reblog by 〜" の表示で ```display_name``` の表示名が空（未設定）のときに
"()" のみを表示しない処理が抜けてたので足しました。
zgock999@末代 さんの BTで確認。
---
=> Also skip empty display_name in Reblog case.

Makefile
Uses ncurses library if building on MacOS
=> Add support for building on MacOS

Makefile.in
現状だと `Makefile.in` の `default` のターゲットで `${MAKE}` を再帰で呼んでいますが、
この再帰で呼ばれる `${MAKE}` には元の `make` 呼び出しで指定された `-f Makefile.bsd` 等の引数が反映されないので
include 元の `Makefile.bsd` にある `CFLAGS` 等が反映されません。
ターゲットとして `nanotodon` を明示的に指定すれば `${MAKE}` が起動されないので動きますが。
```
% make -f Makefile.bsd
make nanotodon
cc -g -DSUPPORT_XDG_BASE_DIR   -c nanotodon.c
nanotodon.c:1:10: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>
^~~~~~~~~~~~~
compilation terminated.
*** Error code 1
Stop.
make[1]: stopped in /s/tsutsui/nanotodon
*** Error code 1
Stop.
make: stopped in /s/tsutsui/nanotodon
% make -f Makefile.bsd nanotodon
cc -g -DSUPPORT_XDG_BASE_DIR -I/usr/pkg/include -I/usr/pkg/include/ncursesw -DNCURSES_WIDECHAR   -c nanotodon.c
cc -g -DSUPPORT_XDG_BASE_DIR -I/usr/pkg/include …
```
=> Use proper default target for make(1).

README.md, nanotodon.c
おそらく `/lock` -> `/private` に変えた時にオフセットが変わってなくて、余計な文字列も一緒に投稿されちゃうので修正です。
それと、README.md に typo っぽいものがあったので一緒に修正してあります。
=> Fix offset character count for /private command (and Typo)

sbuf.c, sbuf.h
この類の警告抑止
```
nanotodon.c:134:18: warning: passing argument 2 of ‘naddstr’ discards ‘const ’ qualifier from pointer target type [-Wdiscarded-qualifiers]
134 |   naddstr(sbctx, dname);
|                  ^~~~~
In file included from nanotodon.c:17:
sbuf.h:21:36: note: expected ‘char *’ but argument is of type ‘const char *’
21 | void naddstr(sbctx_t *sbctx, char *s);
|                              ~~~~~~^
```
ファイル末尾改行漏れも合わせて直しています（というかエディタが勝手に直した）
=> Avoid discard const warnings.

config.h, nanotodon.c, sbuf.c, sixel.c, sixel.h, squeue.c, squeue.h, utils.c, utils.h
`CFLAGS+= -Wall -Wstrict-prototypes -Wmissing-prototypes`
で出る警告抑制です。
修正中に気になった行末スペースとタブ削除も入れてますがこれは余計かも。
=> Appease prototype warnings

Makefile
Both NetBSD and OpenBSD don't require these unless any strict definitions like _POSIX_C_SOURCE and _XOPEN_SOURCE etc. are specified.
---
もともと今の定義は私が適当に提案したという問題がありますが、
CIをかけるならば本質的な警告が紛れないように余計な警告は消したい、となって、
OpenBSD と FreeBSD でも問題ないようなので投げておきます。
結論からすると、
GNU拡張の `timegm(3)` と XPG4 の `strptime(3)` を両方使うには glibc の場合に `_GNU_SOURCE` だけ定義すれば良い
でいいかと。
* Linux (glibc2)
* https://manpages.ubuntu.com/manpages/trusty/man7/feature_test_macros.7.html
によれば
* 何も定義しないと ANSI Cにない XPG4 の関数定義は有効にならない
* `_XOPEN_SOURCE` 等を定義すると、定義された関数定義が有効になる
（つまり定義が広くなる方向）
* `_GNU_SOURCE` を定義するとなんでもありになる
* `_BSD_SOURCE` は過去の「なんでもあり」相当だったが glib 2.20 以降では非推奨
* NetBSD
* man が無いので https://github.com/NetBSD/src/blob/trunk/sys/sys/featuretest.h
を見ると
* 何も定義しないと `_NETBSD_SOURCE` が定義されたのと等価でなんでもありになる
* `_XOPEN_SOURCE` …
=> Remove _BSD_SOURCE for OpenBSD and _NETBSD_SOURCE for NetBSD.

.github/workflows/main.yml
nanotodon本体とは全く関係なく
https://github.com/isaki68k/sayaka/pull/40
と同じ netbsd-vm 他を使った CIの修正です。
> 今まで *BSDのCIで `PATH` が設定されないのはなぜなのだろうと思いつつ手動で書いていたのですが、
> いろいろ見ていたところ netbsd-vm 他の CIのオプション `usesh: true` を設定すると
> https://github.com/vmactions/netbsd-vm/blob/v1.0.8/run.sh
> の `execSSHSH()` で
> ```shell
> #using the sh 
> execSSHSH() {
>   exec ssh "$osname" sh
> }
> ```
> と `-t` 無しで `ssh` を呼んで `sh` を起動するので `~/.profile` が読まれていない、というオチでした。
> 
> そもそも NetBSD および FreeBSD 14.0 以降は root login shell が `/bin/sh` になっていること、
> OpenBSD は root login shell が `/bin/ksh` であるものの CIでは困らないので
> それぞれオプションを削除して `/root/.profile` にあるデフォルトパスが設定されるのも確認しました。
=> CI: remove "usesh: true" to make sure ~/.profile is loaded.

nanotodon.c, sixel.c, sixel.h
rc3 の後に入れる変更じゃないという話もありますが、雑に書いたら動いているっぽいのでとりあえず投げておきます。
* アバターアイコンサイズを「フォントの高さの2倍以上3倍未満でsixel単位の6ドットの倍数」にする (sayaka準拠)
* アバターアイコン表示の後、アイコンの次の行ではなくアイコンの右側に screen name, display name, date/time を表示する
* 起動時の初期化  (`sixel_init()`)で以下を算出
* `TIOCGWINSZ` の `ioctl(2)` で「画面の縦横ピクセル数」と「画面の縦横の行数・桁数」を取得して、それからフォントサイズを算出 (ロジックは sayaka さんから拝借)
* `TIOCGWINSZ` が失敗したらデフォルトサイズを 7x14 にする (これもsayakaさんから拝借)
* アイコンサイズとフォント幅から「screen name他のヘッダ相当行の先頭を右に何文字分動かすか」を算出
* トゥート表示 (`stream_event_update()`) のアイコン表示後の動作を以下の通り変更
* カーソルを1行上に移動
* カーソルをアイコン幅相当文字数分だけ右に移動
* そのまま screen name, display name, date/time 他を表示
* screen name (display name) と date/time で2行に分ける、というのもやってみましたがなんかいまいちでした 
* `print_picture()` を以下の通り変更
*  `mul` 引数の解釈を適当にいじって算出したアイコンサイズで表示するように修正
いずれもAPI変更になるのでここではいじってません。
* `print_picture()` の `mul` …
=> Display avatar icon and screen names etc. as one line header.

sixel.c
FreeBSD と OpenBSD の CI結果見てたら警告出てたので適当に修正しました。
`crc32b()` のほうはつい気になって `const` 付加と `exact int type` を使う修正も入れてます。 (NetBSD盆栽病)
CRC32 を1ビットずつ計算すると遅マシンだと結構重いのでテーブルにしたほうが、
みたいな気もしますが、呼ばれる回数的に https 認証と比べたら大したこと誤差以下かも。
=> Appease -Wall warnings

config.c, config.h, nanotodon.c, nanotodon.h, sbuf.h, sixel.c, sixel.h, squeue.c, squeue.h, utils.c, utils.h
最近静的解析ばかりやってるので目視で気づいたところだけなんとなく修正。
（何かをやった気になるためのコード盆栽ともいう）
* `*.c` で宣言されている関数はローカル扱いで `static` 付与
* ざっと見て変更されない引数は `const` 付与
* 関数プロトタイプから変数名を削除
（これはスタイル定義からですが、ありなし混在してたので）
* プロトタイプについて `char* var` と `char *var` が混在してたところは後者に統一
（これもスタイル定義からですが、後者が多数派っぽいので）
`static` と `const` は inline とかの最適化で効果あるはず、というやつですが計測はしてません。
`hidlckflag` と `noemojiflag` は `monoflag` と同列で export じゃないの、という説もありますが
現状 `nanotodon.h` には無いのと、`monoflag` についてもグローバルにせず
`sixel_init()` と `sixel_out()` (とそれを呼び出している `print_picture()`) の引数で
`mono` か否かを指定すればいいのでは、とか考え出すと止まらないので機械的に `static` にしています。
あと、 `-Wall` だと以下の警告も出ているようですが、意図が把握できていないのでここではいじっていません。
```
sixel.c: In function 'sixel_out':
sixel.c:323:11: warning: unused variable 'delta' [-Wunused-variable]
323 |  uint32_t delta = mul & 0x100 ? 4 : 1;
```
=> Style fixes
